### ISSUE TITLE
git-lfs missing from https://github.com/myroms/roms/wiki

### ISSUE THREAD

**Issue by JamiePringle** [myroms/roms#41]
If you follow the instructions on https://github.com/myroms/roms/wiki for installing roms-test it fails because "git-lfs" is missing.  A line should be added that points the user to https://git-lfs.com to install git-lfs.

**Comment by hga007** [comment]
The **`roms_test`** repository has clear **LFS** instructions at https://github.com/myroms/roms_test. This repository doesn't need LFS support since it ONLY includes source code.
